# services:
#   ros2client:
#     container_name: ros2_jazzy_lpa
#     build: .
#     working_dir: /ros2_ws
#     stdin_open: true
#     tty: true
#     network_mode: host
#     privileged: true
#     environment:
#       - ROS_VERSION=2
#       - ROS_PYTHON_VERSION=3
#       - ROS_DOMAIN_ID=0
#       - ROS_DISTRO=jazzy
#       # - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
#       # - CYCLONEDDS_URI=file:///ros2_ws/cyclone_husarion.xml
#       - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
#       # - ROS_DISCOVERY_SERVER=192.168.8.83:11888
#       # - FASTRTPS_DEFAULT_PROFILES_FILE=/ros2_ws/dds_config.xml
#     volumes:
#       - ./ros2_ws:/ros2_ws

# # - FASTRTPS_DEFAULT_PROFILES_FILE=/ros2_ws/fastrtps_profile.xml

services:
  ros2client:
    container_name: ros2_jazzy_lpa
    build: .
    working_dir: /ros2_ws
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true

    environment:
      - ROS_VERSION=2
      - ROS_PYTHON_VERSION=3
      - ROS_DOMAIN_ID=0
      - ROS_DISTRO=jazzy

      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

    volumes:
      - ./ros2_ws:/ros2_ws

      - /tmp/.X11-unix:/tmp/.X11-unix